export const PATH = {
  ROOT: "/",
  INTRO_PAGE: "/intro",
  SIGNUP_PAGE: "/signup",
  LOGIN_PAGE: "/login",
  ACCOUNT_PAGE: (accountNumber) => `/account/${accountNumber}`,
  GROUP_PAGE: (groupId) => `/group/${groupId}`,
  REGIST_GROUP_PAGE: "/regist-account",
  DEPOSIT_PAGE: (groupId) => `/deposit/${groupId}`,
  TRAVEL_INFO_PAGE: (groupId) => `/travelInfo/${groupId}`,
  INVITATION_PAGE: (groupId) => `/invite/${groupId}`,
  EXCHANGE_PAGE: (groupId) => `/exchange/${groupId}`,
  EXCHANGE_STORE_PAGE: (groupId) => `/exchange/store/${groupId}`,
  CALCULATION_PAGE: (groupId) => `/calculation/${groupId}`,
  TRIPRESULT_PAGE: (groupId) => `/trip/${groupId}`,
  JOINGROUP_PAGE: (link) => `/joinGroup/${link}`,
  TRAVELING_PAGE: (groupId) => `/traveling/${groupId}`,
};
